version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: financeiro_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: financeiro_db
      MYSQL_USER: financeiro_user
      MYSQL_PASSWORD: financeiro_pass
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: .
    container_name: financeiro_api
    restart: always
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: financeiro_user
      DB_PASSWORD: financeiro_pass
      DB_NAME: financeiro_db
      JWT_SECRET: supersecretjwt
    depends_on:
      - db

volumes:
  mysql_data: